### ISSUE TITLE
Stop Breakin' the Innerwebs.......

### ISSUE THREAD

**Issue by BurlesonBrad** [A5hleyRich/wp-scanner#8]
....some of us are actively trying to horse around here!  :horse: 
![wpscanner-down](https://cloud.githubusercontent.com/assets/6208757/15594533/fe5ce916-237b-11e6-9897-3914e79201f9.png)

**Comment by BurlesonBrad** [comment]
Thank You! :+1:

**Comment by A5hleyRich** [comment]
Sorry about that. Our server provider had an unscheduled outage during the night. All back to normal now.
